name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gobrax-data
  REGION: us-central1
  SERVICE: odoo-extractor
  REPOSITORY: odoo-extractor

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "COLOCAR_DEPOIS"
          service_account: "COLOCAR_DEPOIS"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build and Push Image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${SERVICE}:${{ github.sha }} .
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${SERVICE}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${SERVICE}:${{ github.sha }} \
            --region ${REGION} \
            --platform managed \
            --quiet
